const ROUTE_STATE = {
  HOME: {
    SET_HOME: 'ROUTE_STATE.HOME.SET_HOME',
  },
  POST_CONTENT: {
    SET_POST_CONTENT: 'ROUTE_STATE.POST_CONTENT_SET_POST_CONTENT',
  },
};

const ACCOUNT = {
  SET_ACCOUNT: 'ACCOUNT.SET_ACCOUNT',
};
export { ROUTE_STATE, ACCOUNT };
